steps:
  # Install Terraform
  - name: 'hashicorp/terraform:1.5.0'
    args: ['version']
    id: 'tf-version'

  # Initialize Terraform with backend configuration
  - name: 'hashicorp/terraform:1.5.0'
    args: [
      'init',
      '-backend-config=bucket=gorilla-clinic-terraform-state',
      '-backend-config=prefix=terraform/state/${_ENVIRONMENT}'
    ]
    dir: 'terraform/gcp/infra'
    id: 'tf-init'

  # Terraform Plan
  - name: 'hashicorp/terraform:1.5.0'
    args: [
      'plan',
      '-var-file=tfvars/${_ENVIRONMENT}.tfvars',
      '-out=tfplan'
    ]
    dir: 'terraform/gcp/infra'
    id: 'tf-plan'

  # Terraform Apply
  - name: 'hashicorp/terraform:1.5.0'
    args: [
      'apply',
      '-auto-approve',
      'tfplan'
    ]
    dir: 'terraform/gcp/infra'
    id: 'tf-apply'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ENVIRONMENT: prod

timeout: 1800s

serviceAccount: 'projects/assessment-vermaanurag1794/serviceAccounts/petclinic-sa@assessment-vermaanurag1794.iam.gserviceaccount.com'

