steps:
  # Set up authentication for the service account
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'auth'
      - 'activate-service-account'
      - 'petclinic-sa@assessment-vermaanurag1794.iam.gserviceaccount.com'

  # Install Terraform
  - name: 'hashicorp/terraform:1.5.0'
    args: ['version']

  # Initialize Terraform with backend configuration
  - name: 'hashicorp/terraform:1.5.0'
    args: [
      'init',
      '-backend-config=bucket=gorilla-clinic-terraform-state',
      '-backend-config=prefix=terraform/state'
    ]
    dir: 'terraform/environments/prod'
    env:
      - 'GOOGLE_CLOUD_SERVICE_ACCOUNT=petclinic-sa@assessment-vermaanurag1794.iam.gserviceaccount.com'

  # Terraform Plan
  - name: 'hashicorp/terraform:1.5.0'
    args: [
      'plan',
      '-var-file=prod.tfvars',
      '-out=tfplan'
    ]
    dir: 'terraform/environments/prod'
    env:
      - 'GOOGLE_CLOUD_SERVICE_ACCOUNT=petclinic-sa@assessment-vermaanurag1794.iam.gserviceaccount.com'

  # Terraform Apply
  - name: 'hashicorp/terraform:1.5.0'
    args: [
      'apply',
      '-auto-approve',
      'tfplan'
    ]
    dir: 'terraform/environments/prod'
    env:
      - 'GOOGLE_CLOUD_SERVICE_ACCOUNT=petclinic-sa@assessment-vermaanurag1794.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
  serviceAccount: 'projects/assessment-vermaanurag1794/serviceAccounts/petclinic-sa@assessment-vermaanurag1794.iam.gserviceaccount.com'

substitutions:
  _ENVIRONMENT: prod

timeout: 1800s
